### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Damien-Matthews** [Dev-CasperTheGhost/snaily-cadv3#109]
**Describe the bug**
When using the discord webhook, I noticed that the callsign, and the officers name and callsign are conjoined together.

**To Reproduce**

1. Set a valid webhook URL within the admin panel.
2. Go to the LEO Dashboard, and go on duty.
3. Look at the readout from the discord webhook

**Expected behavior**
A space or a space and a vertical line separating the officers name and callsign.

**Screenshots**
https://prnt.sc/10ic0b9
^ screenshot

**Desktop (please complete the following information):**

Discord with CAD Version 1.4.0

**Additional context**
N/A

**Comment by Dev-CasperTheGhost** [comment]
Whoops, that’s my bad. I’ll fix it in the next release:)
