### ISSUE TITLE
Bug on tow and taxi screen.

### ISSUE THREAD

**Issue by Wolf1911** [Dev-CasperTheGhost/snaily-cadv3#112]
The location, description, and caller are backwards for the active tow calls section.

**Comment by Dev-CasperTheGhost** [comment]
I'll look into it!

**Comment by Wolf1911** [comment]
Are we able to edit grammar and such? Just random spelling problems here and there that wouldn't necessarily need a bug report for each one.

Also want to take out the EMS/FD "Deputies." Doesn't really make sense because Fire and EMS aren't deputies.

**Comment by Dev-CasperTheGhost** [comment]
> 
> 
> Are we able to edit grammar and such? Just random spelling problems here and there that wouldn't necessarily need a bug report for each one.
> 
> Also want to take out the EMS/FD "Deputies." Doesn't really make sense because Fire and EMS aren't deputies.

Meh. feel free to open 1 issue and edit the description/add a comment for a the spelling mistakes 



> Also want to take out the EMS/FD "Deputies." Doesn't really make sense because Fire and EMS aren't deputies.

What should I call them? Or just completely remove the word "Deputies"

**Comment by Wolf1911** [comment]
FD/EMS Member would be good. Thanks for getting back to me.

**Comment by Dev-CasperTheGhost** [comment]
Alright, so you can change the FD/EMS stuff in the `client/src/languages.json` file. I can't since I might screw over other people ones. The EMS/FD stuff should be at the bottom of the file :)
