### ISSUE TITLE
[Bug] Unable to create officer

### ISSUE THREAD

**Issue by bound2** [Dev-CasperTheGhost/snaily-cadv3#123]
**Describe the bug**
Unable to add new officers in a fresh install of snaily-cad.

Error in logs:
```
[unhandledRejection][13:32:23]: Error: ER_NO_DEFAULT_FOR_FIELD: Field 'started_at' doesn't have a default value
```

**To Reproduce**

1. Go to Admin panel
2. Click on Departments
3. Add a new department
4. Go to Police dept panel
5. Click on My officers
6. Click on Create An Officer button
7. Fill in callsign, name and choose department from dropdown menu
8. Click Create Officer button

**Expected behavior**
An officer would be created. No errors in the logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/9380102/111906777-feb69380-8a5a-11eb-9c4a-f3d1ff3a0698.png)

**Desktop (please complete the following information):**

- Browser [e.g. chrome, safari] - Firefox Windows
- Version [e.g. 22] - 86.0.1

**Additional context**

**Comment by Dev-CasperTheGhost** [comment]
Run this in the phpmyadmin panel in the `officers` table:

```sql
ALTER TABLE `officers` DROP `started_at`;
```

**Comment by bound2** [comment]
Could it be an issue of `database.ts`? On line 49 you do alter table to drop it, but on line 60 there's another alter table to add it

**Comment by Dev-CasperTheGhost** [comment]
oh bruh. That's my bad, I'll remove it soon

**Comment by bound2** [comment]
Have you thought about using liquibase for database migration management?

**Comment by Dev-CasperTheGhost** [comment]
> 
> 
> Have you thought about using liquibase for database migration management?

Haven't heard of it. But I'll check it out, thanks!

**Comment by Dev-CasperTheGhost** [comment]
I've removed the line where it was adding it again. Imma checkout liquibase for the migrations

**Comment by bound2** [comment]
Receiving new error after pulling the fix. This time I'm not able to register an account. Fresh install.
![image](https://user-images.githubusercontent.com/9380102/111908206-05480980-8a61-11eb-9d39-1aeb8141f6ed.png)

**Comment by Dev-CasperTheGhost** [comment]
use this:

```sql
ALTER TABLE `cad_info` ADD `steam_api_key` varchar(255) NOT NULL AFTER `webhook_url`;
```

**Comment by bound2** [comment]
I see that it's present under database.ts, but how come it didn't apply it

**Comment by Dev-CasperTheGhost** [comment]
Yeah, I wouldn't know that xd. It's weird tho
