### ISSUE TITLE
Clicking on dropdown menu, which doesn't have items, makes whole screen black

### ISSUE THREAD

**Issue by henriots** [Dev-CasperTheGhost/snaily-cadv3#127]
**Describe the bug**
When clicking on dropdown menu, which has no items, results in black screen. Only way to get back is to reload webpage

**To Reproduce**

1. Go to 'weapons/register' (however, this occures with all dropdown lists)
2. Click on 'Enter Weapon dropdown' when not having anything defined
3. Screen is black and have to refresh the page

**Expected behavior**
Should show empty list instead

**Screenshots**

**Desktop (please complete the following information):**

- Browser Chrome
- Version 89

**Comment by Dev-CasperTheGhost** [comment]
Try running `npm run translation:generate`

**Comment by henriots** [comment]
At the moment, itt's built on dev branch, because docker things are not merged to main

**Comment by Dev-CasperTheGhost** [comment]
Alright. Running the translation & build command should fix it

**Comment by henriots** [comment]
Is translation running required then on every start?

**Comment by Dev-CasperTheGhost** [comment]
When there’s a new update, it’s required to build the client and generate the translations.

**Comment by henriots** [comment]
Mm then I don't get it how running `npm run translation:generate` would fix it.
How is our deploy process:
- Checkout snaily-cadv3 branch
- Build container based on the branch: client will be built and translations generated and copyed to the final container
- Deploy that specific container to live, which specific tag matches git commit hash

I would understand if dev branch in general is broken.

**Comment by Dev-CasperTheGhost** [comment]
Ah, I’ll look into it when I’m home

**Comment by Dev-CasperTheGhost** [comment]
Alright, looks like I messed up a small thing. I'll push a fix very soon :)

**Comment by Dev-CasperTheGhost** [comment]
This [commit (`b361068`)](https://github.com/Dev-CasperTheGhost/snaily-cadv3/commit/b36106885708aad28e0377fa6ef4ca3fac0343df) should've fixed it

**Comment by henriots** [comment]
Thanks!

Tested and it works
