### ISSUE TITLE
[FEATURE REQUEST]: Make menubar auto-close when using CAD on lower resolutions

### ISSUE THREAD

**Issue by henriots** [Dev-CasperTheGhost/snaily-cadv3#129]
**Describe the feature you'd like to get added**
At the moment, menubar doesn't auto-close when clicking on menu entries. This is kind of annoying when running this CAD in-game in a lower resolution as you have to manually close it every time

**Comment by Dev-CasperTheGhost** [comment]
This is fixed in dev, will be released soon :D

**Comment by Dev-CasperTheGhost** [comment]
Fixed in `1.4.8` :D
