### ISSUE TITLE
[FEATURE REQUEST]: Do not allow special characters in usernames

### ISSUE THREAD

**Issue by henriots** [Dev-CasperTheGhost/snaily-cadv3#130]
**Describe the feature you'd like to get added**
People are registring with usernames that have, for example, spaces in them, which might not be very ideal. I haven't dug into very detail what and how username validation should be handled, so you might have to do some research.

**Additional context**
However, those users which have already registered, should be able to keep their usernames.

**Comment by Dev-CasperTheGhost** [comment]
> for example, spaces in them

I can check for special characters such as `@#[[^$µ%...`, not sure if spaces are worth?

**Comment by henriots** [comment]
In my opinion, atleast spaces shouldn't be allowed in usernames

**Comment by bound2** [comment]
It's more complex than that. You should take into account the possibilities of cyrillic characters, emojis etc. Ideally username wouldn't start / end with . _ or - whereas it should be allowed as a separator character e.g. **first.last**, **first_last** (not **_first.last-**).

**Comment by Dev-CasperTheGhost** [comment]
True, the "fix" I implemented was just a simple fix for now. There might be a package that I can use for it, but I'll look into that

**Comment by Dev-CasperTheGhost** [comment]
I might've found a package that I can use. Tho, it would remove the special characters rather than check for special characters. I have a few ideas to still show them an error message if they have special characters

**Comment by Dev-CasperTheGhost** [comment]
I'll keep this open for now, but this has been partially fixed in `1.4.8`
