### ISSUE TITLE
Forgot Password Feature

### ISSUE THREAD

**Issue by DylanReynolds12** [Dev-CasperTheGhost/snaily-cadv3#148]
**Describe the feature you'd like to get added**
"Forgot password" this would be a nice feature as some of my members forgot there password so had to remove there accounts.... or a option for cad admins to reset a users password to a temp password.

**Additional context**

**Comment by Dev-CasperTheGhost** [comment]
I'll probably only add the ability for admins to add temp passwords. Maybe only add an option so only selected admins can change passwords

**Comment by Dev-CasperTheGhost** [comment]
this will be added in the next release :D. You [can follow progress here](https://github.com/Dev-CasperTheGhost/snaily-cadv3/pull/147)
