### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DylanReynolds12** [Dev-CasperTheGhost/snaily-cadv3#149]
**Describe the bug**
it shows the bug in the screenshot

**To Reproduce**

1. Download newest verison
2. npm start 

**Expected behavior**
I expected this to start the cad

**Screenshots**
![image](https://user-images.githubusercontent.com/25635607/113504717-71039980-956c-11eb-80d5-75f36e0757b5.png)

**Desktop (please complete the following information):**

- Version Newest w/ Temp passwords

**Additional context**

**Comment by Dev-CasperTheGhost** [comment]
Looks like something went wrong when doing `git pull origin main`. Can you double check you ran that command correctly?
