### ISSUE TITLE
Login header

### ISSUE THREAD

**Issue by jdakota** [Dev-CasperTheGhost/snaily-cadv3#154]
**Describe the feature you'd like to get added**

Remove the navigation bar for users that arent logged in. 

**Additional context**

**Comment by ItsWrath** [comment]
Was also going to recommend this, it makes everything a little less confusing for some users.

**Comment by Dev-CasperTheGhost** [comment]
Will be added in the next release :D

**Comment by Dev-CasperTheGhost** [comment]
This has just been added in 2.0.2 🎉!
