### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by jdakota** [Dev-CasperTheGhost/snaily-cadv3#156]
**Describe the feature you'd like to get added**
Allow admins to create accounts versus members to stop spam accounts from being created or allow us to create a code for users to use to register accounts or allow communities to choose weather users can create their own accounts or if admins should create the accounts for the users.

**Additional context**

**Comment by Dev-CasperTheGhost** [comment]
> or allow us to create a code for users to use to register accounts

this should be possible. Might be added in the next release

**Comment by Dev-CasperTheGhost** [comment]
This has been added 🎉. Make sure to update your CAD and head over to the CAD-settings.
