### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by ItsSimko** [Dev-CasperTheGhost/snaily-cadv3#176]
**Describe the bug**
When I run NPM Start it does not start and gives me a error log.

**To Reproduce**
run npm start

**Expected behavior**
Start the app

**Screenshots**
![image](https://user-images.githubusercontent.com/5206105/116825516-ab595a00-ab5d-11eb-94a9-bc708e02127c.png)

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle snaily-cadv3@2.0.9~prestart: snaily-cadv3@2.0.9
6 info lifecycle snaily-cadv3@2.0.9~start: snaily-cadv3@2.0.9
7 verbose lifecycle snaily-cadv3@2.0.9~start: unsafe-perm in lifecycle true
8 verbose lifecycle snaily-cadv3@2.0.9~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\snaily-cadv3\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle snaily-cadv3@2.0.9~start: CWD: C:\snaily-cadv3
10 silly lifecycle snaily-cadv3@2.0.9~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run translation:generate && npm run build && cross-env NODE_ENV=production node dist/server.js'
10 silly lifecycle ]
11 silly lifecycle snaily-cadv3@2.0.9~start: Returned: code: 134  signal: null
12 info lifecycle snaily-cadv3@2.0.9~start: Failed to exec start script
13 verbose stack Error: snaily-cadv3@2.0.9 start: `npm run translation:generate && npm run build && cross-env NODE_ENV=production node dist/server.js`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid snaily-cadv3@2.0.9
15 verbose cwd C:\snaily-cadv3
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 134
22 error snaily-cadv3@2.0.9 start: `npm run translation:generate && npm run build && cross-env NODE_ENV=production node dist/server.js`
22 error Exit status 134
23 error Failed at the snaily-cadv3@2.0.9 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]

**Desktop (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by Dev-CasperTheGhost** [comment]
@ItsSimko try re-installing the CAD to your documents/desktop folder. npm doesn't always have the correct permissions to install directly to the Users folder/C Drive

**Comment by ItsSimko** [comment]
![image](https://user-images.githubusercontent.com/5206105/116826245-0d678e80-ab61-11eb-9456-0392404058bc.png)
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle snaily-cadv3@2.0.9~prestart: snaily-cadv3@2.0.9
6 info lifecycle snaily-cadv3@2.0.9~start: snaily-cadv3@2.0.9
7 verbose lifecycle snaily-cadv3@2.0.9~start: unsafe-perm in lifecycle true
8 verbose lifecycle snaily-cadv3@2.0.9~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Administrator\Documents\snaily-cadv3\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle snaily-cadv3@2.0.9~start: CWD: C:\Users\Administrator\Documents\snaily-cadv3
10 silly lifecycle snaily-cadv3@2.0.9~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run translation:generate && npm run build && cross-env NODE_ENV=production node dist/server.js'
10 silly lifecycle ]
11 silly lifecycle snaily-cadv3@2.0.9~start: Returned: code: 3221225725  signal: null
12 info lifecycle snaily-cadv3@2.0.9~start: Failed to exec start script
13 verbose stack Error: snaily-cadv3@2.0.9 start: `npm run translation:generate && npm run build && cross-env NODE_ENV=production node dist/server.js`
13 verbose stack Exit status 3221225725
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid snaily-cadv3@2.0.9
15 verbose cwd C:\Users\Administrator\Documents\snaily-cadv3
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 3221225725
22 error snaily-cadv3@2.0.9 start: `npm run translation:generate && npm run build && cross-env NODE_ENV=production node dist/server.js`
22 error Exit status 3221225725
23 error Failed at the snaily-cadv3@2.0.9 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225725, true ]

This is the errors I get now.

**Comment by Dev-CasperTheGhost** [comment]
Never seen this before. I’ll need to look into it tomorrow when I wake up

**Comment by ItsSimko** [comment]
Thank you, any help will be apreciated.

**Comment by Dev-CasperTheGhost** [comment]
@ItsSimko are you using the .env file or using the config.ts?

**Comment by ItsSimko** [comment]
config.ts

**Comment by Dev-CasperTheGhost** [comment]
Can you try removing the following folders and files

- `dist/`
- `node_modules/`
- `.next/`
- `package-lock.json`

Then run `npm install` again. Then start the CAD

**Comment by ItsSimko** [comment]
Okay, so I didn't have some of these folders, upon trying to build when I deleted package-lock.json it prompt me that my npm was outdated. One update later and I have none of the errors I had before. However, now I am getting different errors.

![image](https://user-images.githubusercontent.com/5206105/116908951-82929c80-ac11-11eb-934e-0d71550a58ac.png)

About how much ram does this CAD use? as I think it is a ram issue on my box as I am running a fairly low ram box.

**Comment by Dev-CasperTheGhost** [comment]
When building it can take a bit (sometimes), but when started it shouldn't take too much. So yeh, It can be a RAM issue.

**Comment by ItsSimko** [comment]
Alright, looks like it is a ram issue after more testing. Thanks for the help cant wait to use this for my community! :)

**Comment by Dev-CasperTheGhost** [comment]
Yep, no problem!
