### ISSUE TITLE
Shared Citizen

### ISSUE THREAD

**Issue by sinphoenix** [Dev-CasperTheGhost/snaily-cadv3#181]
It would be nice if everyone with PD, EMS, DOJ, and Admin could see all citizens created. Then it would be more like an actual MDT device. Reports, Medical records, Profiles, lic, cars, wepaons, all synced so that Dispath can actually look up people and plates. As it sets now, everyone needs to create the same citizen and update that profile when anything happens

**Comment by Dev-CasperTheGhost** [comment]
Currently admin, leo and dispatch can see information about citizens. I’ll see what I do with this

**Comment by sinphoenix** [comment]
PD officer created a Citizen. Another Officer was clocked on but could not
see that citizen at all

**Comment by Dev-CasperTheGhost** [comment]
> PD officer created a Citizen. Another Officer was clocked on but could not
see that citizen at all

What do you mean with "Could not see that citizen at all"? 

1. Could not see that citizen in the /citizen page
2. Could not search the citizen via name search.
3. Other, explain.

**Comment by Dev-CasperTheGhost** [comment]
> They would appear but would give me an error, and said to contact CAD Owner
> […](#)

I’ll look into it soon

**Comment by sinphoenix** [comment]
seen that and updated my dude thank you!

There away to change Prison time to Months? i mean every city ive been in
has there time set to months, which in city is minutes.

if you need anything else to help you with this let me know. i fill these
out daily IRL lol

**Comment by Dev-CasperTheGhost** [comment]
> There away to change Prison time to Months? i mean every city ive been in
has there time set to months, which in city is minutes.

In the CAD this is set to seconds because there's a jail script that uses seconds. It's easier to quickly see the total time in seconds
