### ISSUE TITLE
[FEATURE REQUEST]: Being able to provide an alternate port to MySQL

### ISSUE THREAD

**Issue by Ghostz0r** [Dev-CasperTheGhost/snaily-cadv3#182]
It would be nice to provide a custom port for the MySql server in the config file. As of now I didn't found a way to do so.

**Comment by Ghostz0r** [comment]
Hi, I just fixed the issue I had by adding some code to the configs. Here's the changes in case you want to implement them. It's my first time working with this language but I think I didn't miss anything.
https://github.com/Ghostz0r/snaily-cadv3/commit/809addf7b80892c8155922f7cbd4c860c0cdb73b

**Comment by Dev-CasperTheGhost** [comment]
Yup. Looks good. Will implement these changes today

**Comment by Dev-CasperTheGhost** [comment]
This will be included in the next release.

**Comment by Ghostz0r** [comment]
Glad to have helped
