### ISSUE TITLE
[Bug] Registration not working

### ISSUE THREAD

**Issue by TechDude98** [Dev-CasperTheGhost/snaily-cadv3#21]
**Describe the bug**
When trying to register for the first time, it does not work correctly. It just sits on the register page and does not process.

**Expected behavior**
To register the first admin account.

**Desktop (please complete the following information):**
 - Browser: tried Chrome, Opera, Firefox and IE

**Comment by Dev-CasperTheGhost** [comment]
Are you getting any errors in your browser console? Or in the main console?

**Comment by TechDude98** [comment]
So interestingly.. I am running this in an AWS EC2 Instance, and when I tried to run `npm run build` in the client folder, it came up with this:

ubuntu@cad:~/snaily-cadv3/client$ npm run build

> client@1.0.0 build /home/ubuntu/snaily-cadv3/client
> react-scripts build

Creating an optimized production build...
The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@1.0.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-11-03T16_26_40_274Z-debug.log

**Comment by TechDude98** [comment]
Might have to upgrade my VPS.. lol - but it was coming up with an error about localhost:3000 not matching the IP or domain name.

**Comment by Dev-CasperTheGhost** [comment]
Yea, you have to change the `localhost` in `client/src/config.ts` to the IP or domain name of your instance. And make sure it matches the one in `server/config.ts`, make sure to run `npm run build` in both folders after updating it

**Comment by Dev-CasperTheGhost** [comment]
so for me it would be: my example IP is c

My server is running on port: 3030
Client is running on port 80

Server config: 

```js
const config = {
  port: 3030,
  clientUrl: "http://99.99.99.99",
  host: "localhost",
  user: "root",
  password: "admin",
  databaseName: "snaily-cad",
  jwtSecret: "bongo super cat",
  env: "production", /* Do NOT change this unless you know what you are doing! */
};

export default config;
```

Client config: 

```js
const SERVER_URL = "http://99.99.99.99:3030";

export default SERVER_URL;
```

Hope you understand.
