### ISSUE TITLE
Can't allow Iframe usage

### ISSUE THREAD

**Issue by ImBrendano** [Dev-CasperTheGhost/snaily-cadv3#214]
For some reason when changing `allowIframes: false` to true it's not only not allowing Iframes but also denying browser access as well. Thanks for your help Casper! :)

**Comment by Dev-CasperTheGhost** [comment]
Hey, 

Due to new cookie regulations that don't allow Cross-Site cookies anymore, you need an SSL Certificate for your domain (`https`) to have this CAD/MDT work in iframes/cross-sites.

Once you've got your SSL certificate, you need to enable `secureCookie` in the `config.ts`:

```ts
allowIframes: true,
secureCookie: true,
```

**Comment by ImBrendano** [comment]
Ahh, I was wondering if that was the case too I just didn't have the ssl cert. I appreciate it. Btw are you really 15?

**Comment by Dev-CasperTheGhost** [comment]
> Btw are you really 15?

For those interested: yes, I'm 15 at the time of posting this comment.

**Comment by Dev-CasperTheGhost** [comment]
I'll keep this issue open for others too see. Maybe it helps them too

**Comment by ImBrendano** [comment]
Damn man, I'm 21 and you're a far better coder than me.

**Comment by ImBrendano** [comment]
Have the domain with ssl but I'm getting ERR_SSL_PROTOCOL_ERROR not sure what to do

**Comment by mitchal01** [comment]
If your using Linux Ubuntu (This is what I am currently running and it works)

Use Nginx to help out 

@Nap14hockey#1957 Posted this at the right time

sudo apt update
sudo apt install -y certbot
# Run this if you use Nginx
sudo apt install -y python3-certbot-nginx

# Nginx
certbot certonly --nginx -d example.com

# Standalone - Use this if ngnix does not works. Make sure to stop your webserver first when using this method.
certbot certonly --standalone -d example.com


#sites-enable config

server {
  listen       80;
  listen       443 ssl;
  server_name  <DOMAIN NAME HERE>;

    ssl_certificate        <Directory to certs>/fullchain.pem;
    ssl_certificate_key     <Directory to certs>/privkey.pem;
    ssl_trusted_certificate <Directory to certs>/chain.pem;

  location / {
    proxy_pass http://localhost:3030;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}

As well @Dev-CasperTheGhost  This could also help in the Wiki for Ngnix

**Comment by Dev-CasperTheGhost** [comment]
Will add it to the wiki soon
