### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by williamson462** [Dev-CasperTheGhost/snaily-cadv3#22]
May be add webhook for discord? Ie call logs etc.

**Comment by williamson462** [comment]
To add discord intergration into cad, apart from that everything is excellent! May be add some more things to it, may be a community chat or something. :)

**Comment by Dev-CasperTheGhost** [comment]
Ill see when i get some time for this.

**Comment by Dev-CasperTheGhost** [comment]
This feature is released for 911 calls. I will add tow calls aswell later on. Make sure to update your CAD and goto CAD settings and paste in your webhook url
