### ISSUE TITLE
Docker installation failed

### ISSUE THREAD

**Issue by BlutwurstPro** [Dev-CasperTheGhost/snaily-cadv3#226]
### What version of Node.js are you using?

14.17.2

### What version of npm are you using?

6.14.13

### What operating system are you using?

Debian 10

### Describe the Bug

When starting the cad with docker, the following error happens:
![2021-07-23 19_41_22 - PuTTY](https://user-images.githubusercontent.com/10463210/126821242-031bbc9f-7d9c-480c-9d88-c1c23a636594.png)

the only change I made was changing the phpmyadmin port to 9090 instead of 8080

### Expected Behavior

The CAD should start

### To Reproduce

follow instructions in the wiki an change phpmyadim port to 9090

**Comment by Dev-CasperTheGhost** [comment]
Will look into it as soon as I can. I’m currently on vacation tho

**Comment by Dev-CasperTheGhost** [comment]
This has been fixed in `dev`. Will be fully fixed in the next release!
