### ISSUE TITLE
Error Code 500 But Still Works

### ISSUE THREAD

**Issue by RealZotty** [Dev-CasperTheGhost/snaily-cadv3#228]
### What version of Node.js are you using?

v10.19.0

### What version of npm are you using?

6.14.4

### What operating system are you using?

Ubuntu

### Describe the Bug

Whenever changing someones employment rank on a company or approving someone to a company it shows an error code 500 in the top right even tho the action was actually performed it just doesnt say/show it was until you refresh the page

### Expected Behavior

I accept to click accept and then them be removed from pending and put under employees

### To Reproduce

To reproduce this issue you can try and join a whitelisted company as a different civ then as the owner try to accept them

**Comment by Dev-CasperTheGhost** [comment]
Any errors in your terminal?

**Comment by RealZotty** [comment]
![image](https://user-images.githubusercontent.com/73736935/127557272-d09e258a-7063-4bdf-83d0-a891287c352b.png)

**Comment by Dev-CasperTheGhost** [comment]
@RealZotty this looks like a db issues. Make sure you imported the snaily-cad.sql correctly. Feel free to re-open this if you're still encountering this issue
