### ISSUE TITLE
[FEATURE REQUEST]: Search entity by part of number

### ISSUE THREAD

**Issue by pp2amd6** [Dev-CasperTheGhost/snaily-cadv3#245]
**Functional**
Add the ability to search for entities (vehicles, weapons) by part of the number (min. 3 characters)

**Behavior now**
Veh. number:
![perU9w0 1](https://user-images.githubusercontent.com/4976837/135762837-ff934b00-d775-4859-8967-c9879446957b.jpg)

Search:
![qioFOZp 1](https://user-images.githubusercontent.com/4976837/135762909-53c2b8ca-cc9b-43c3-bd7f-e30a9b51150c.jpg)

**Comment by Dev-CasperTheGhost** [comment]
https://github.com/SnailyCAD/snaily-cadv4/issues/64
