### ISSUE TITLE
[FEATURE REQUEST]: Sorting list values

### ISSUE THREAD

**Issue by pp2amd6** [Dev-CasperTheGhost/snaily-cadv3#246]
Add sorting of list values: vehicle names, weapon names, types, etc.

Many lists are sorted by the id field from the database table.

I would like to be able to choose the sorting type for the list: alphabetically (a - z or z -a) or your own sort order (specifying sortindex, for example, for penalcode)

Wrong sorting:
![ct0SBv6 1](https://user-images.githubusercontent.com/4976837/135764618-0b345cd3-070a-4a56-85ec-c206e8176c14.jpg)

Correct sorting:
![63Qwt96 1](https://user-images.githubusercontent.com/4976837/135764797-5e6f8e9f-2108-4062-afe0-9285eb537f8b.jpg)

**Comment by Dev-CasperTheGhost** [comment]
This feature has been implemented in https://github.com/SnailyCAD/snaily-cadv4
