### ISSUE TITLE
[FEATURE REQUEST]: Simplify citizens panel

### ISSUE THREAD

**Issue by pp2amd6** [Dev-CasperTheGhost/snaily-cadv3#249]
I suggest removing the "Logout" and "Account" buttons on the citizen's panel, because they are present in the Account section (top right)

![Hp7icKz 1](https://user-images.githubusercontent.com/4976837/135800270-4a2ad192-5872-429f-aee9-287c6995bd97.jpg)

**Comment by Dev-CasperTheGhost** [comment]
This feature has been implemented in https://github.com/SnailyCAD/snaily-cadv4
