### ISSUE TITLE
[FEATURE REQUEST]: Confirmation for deleting items

### ISSUE THREAD

**Issue by pp2amd6** [Dev-CasperTheGhost/snaily-cadv3#250]
In the case when we delete elements, CAD does not ask for confirmation of the action. This means that something can be deleted by mistake.

I would like to see a confirmation mechanism for deleting in the form of a simple modal window with "yes" and "no" buttons

**Comment by Dev-CasperTheGhost** [comment]
This feature has been implemented in https://github.com/SnailyCAD/snaily-cadv4
