### ISSUE TITLE
Docker Fails to Start snailycad-web

### ISSUE THREAD

**Issue by ElectricityMachine** [Dev-CasperTheGhost/snaily-cadv3#255]
### What version of Node.js are you using?

14.18.1

### What version of npm are you using?

6.14.15

### What operating system are you using?

Debain 11

### Describe the Bug

Docker version: 20.10.5+dfsg1, build 55c4c88
Docker-Compose version: 1.29.2, build 5becea4c

Running the docker-compose command provided in the Wiki after editing my .env file to my needs results in this:

![image](https://user-images.githubusercontent.com/47489506/138990541-a89cc36f-4b61-419d-a95a-6e8b7b114f84.png)

![image](https://user-images.githubusercontent.com/47489506/138990631-3e59c458-a415-4e1e-aefc-4280688eff69.png)

This repeats until I Ctrl+C, where it successfully shuts down.

### Expected Behavior

No errors and the Docker container starts up.

### To Reproduce

```
git clone https://github.com/Dev-CasperTheGhost/snaily-cadv3
cd snaily-cadv3
nano .env
(edit .env file)
sudo docker-compose --env-file .env up
```

**Comment by Dev-CasperTheGhost** [comment]
Hey, this looks likes Docker has insufficient permissions. Will be closing this issue since this doensn't really have anything to do with SnailyCADv3
