### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by keatans** [Dev-CasperTheGhost/snaily-cadv3#39]
hello I have these errors during the installation I corrected it by deleting and reinstating as requiring me di that I am co but impossible to connect me to the DB

ng: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?)' at line 1

![Capture2](https://user-images.githubusercontent.com/51285908/100616763-dc690080-3319-11eb-9071-97ae24de1096.PNG)
![Capture3](https://user-images.githubusercontent.com/51285908/100616764-dd019700-3319-11eb-91b9-077954eff2d1.PNG)
![Capture4](https://user-images.githubusercontent.com/51285908/100616766-de32c400-3319-11eb-8191-569a5fae6258.PNG)
snaily-cadv2 or not prob
thinks

**Comment by Dev-CasperTheGhost** [comment]
Make sure you use the latest version of the database, if you were using snaily-cadv2, unfortunately you'll have to use a clean database. The updated database .sql file is in the root "snaily-cad.sql"

**Comment by keatans** [comment]
Yes obviously and I even have this error at the beginning I have installed the v3 but does not work for me so try the v2 which works but by installing the v3 yes I take the sql v3

**Comment by Dev-CasperTheGhost** [comment]
Can you send me a screenshot of what errors you're getting now?

**Comment by keatans** [comment]
I have sent you all my errors the console gives me nothing more and my web page l the error that I wrote but in I want to connect nothing happens as if the DB and not linked to the installation I have them  errors send in screenshot

**Comment by keatans** [comment]
[
![Capture5](https://user-images.githubusercontent.com/51285908/100649395-ab50f600-3342-11eb-986f-c7c9f8923d5f.PNG)
![Capture11](https://user-images.githubusercontent.com/51285908/100649397-abe98c80-3342-11eb-9e67-c0a820a37b6f.PNG)
it's ok??
while installation error
![Capture2](https://user-images.githubusercontent.com/51285908/100649611-f9fe9000-3342-11eb-94b2-84709304838d.PNG)
![Capture3](https://user-images.githubusercontent.com/51285908/100649613-fa972680-3342-11eb-85b0-7e1c5f3fe8cd.PNG)
![Capture4](https://user-images.githubusercontent.com/51285908/100649619-fbc85380-3342-11eb-8709-065d24969667.PNG)
](url)

**Comment by Dev-CasperTheGhost** [comment]
Try installing ``npm install socket.io@2.3.0`` in the server folder

**Comment by keatans** [comment]
npm install socket.io@2.3.0 with its more error while installing after modifying my configuration I get this error

my config actual

const config = {
  port: 3030,
  clientUrl: "http://localhost:5000",
  host: "127.0.0.1",
  user: "root",
  password: "",
  databaseName: "snaily-cad",
  jwtSecret: "bongo super cat",
  env: "production", /* Do NOT change this unless you know what you are doing! */
};

const SERVER_URL = "http://192.168.1.90:3030";
export default SERVER_URL;

![Capture6](https://user-images.githubusercontent.com/51285908/100733451-7d18f800-33ce-11eb-9473-d0da1bde525b.PNG)
thinks for help

**Comment by keatans** [comment]
npm install socket.io@2.3.0 with its more error while installing after modifying my configuration I get this error
my config actual
const config = {
  port: 3030,
  clientUrl: "http://localhost:5000",
  host: "127.0.0.1",
  user: "root",
  password: "",
  databaseName: "snaily-cad",
  jwtSecret: "bongo super cat",
  env: "production", /* Do NOT change this unless you know what you are doing! */
};
export default config;
const SERVER_URL = "http://192.168.1.90:3030";
export default SERVER_URL;

![Capture6](https://user-images.githubusercontent.com/51285908/100733943-38419100-33cf-11eb-84cf-6f7a6cb24474.PNG)
thinks for help

**Comment by keatans** [comment]
Error solved by a friend
**File**: ./server/src/routes/auth.ts
**Error**:` [username, "Change me", "Change me", "0", "0", "0"]` to `[username, "Change me", "Change me", "0", "0", "0", "0"]` (l77)

**Comment by Dev-CasperTheGhost** [comment]
alright, thanks! I'll look into this soon

**Comment by Dev-CasperTheGhost** [comment]
This issue has just been fixed! Thanks for reporting this issue.
