### ISSUE TITLE
[Bug] Cannot find config

### ISSUE THREAD

**Issue by AidanDaDoolphin** [Dev-CasperTheGhost/snaily-cadv3#50]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75757790/101698876-41be9f00-3a48-11eb-9f5a-77e8af3ff77e.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by Dev-CasperTheGhost** [comment]
Please provide more info
