### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by arcadejackpotmaster** [Dev-CasperTheGhost/snaily-cadv3#52]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
I cannot get the cad setup correctly I tried what I did with v2 and it wasn't working. CAN YOU ADD ME ON DISCORD 
arcadejackpotmaster#9999 
Thanks 
Austin 
![what do i do ](https://user-images.githubusercontent.com/47673794/102004552-97a07a80-3cc6-11eb-99bc-fa2fd21a051a.PNG)

**Comment by Dev-CasperTheGhost** [comment]
Please read the error, the config file for `server` cannot be found.

**Comment by Dev-CasperTheGhost** [comment]
Oh, I'm also not accepting friend requests anymore.

**Comment by arcadejackpotmaster** [comment]
is this how the server file should look?
![www](https://user-images.githubusercontent.com/47673794/102018929-41aeef80-3d25-11eb-86ff-1980e9d9b1be.PNG)

**Comment by Dev-CasperTheGhost** [comment]
Yes

**Comment by Dev-CasperTheGhost** [comment]
Wait, theres 2 dots for the config file, make it one

**Comment by arcadejackpotmaster** [comment]
![ok now what](https://user-images.githubusercontent.com/47673794/102020578-e124b000-3d2e-11eb-91b9-6623cae02556.PNG)
what now

**Comment by Dev-CasperTheGhost** [comment]
Try to run this command in the server folder: `npm install socket.io@2.3.0`

**Comment by Dev-CasperTheGhost** [comment]
This issue has just been fixed, make sure to update to the latest version.
